### ISSUE TITLE
The dataset in the original order

### ISSUE THREAD

**Issue by lighter47** [katherinethai/par3#1]
Hi, thank you for your great work. I noticed that the original order of the paragraphs had been shuffled. Could you please provide the dataset in the original order? I need this data for some analysis. I would really appreciate it.

**Comment by katherinethai** [comment]
Hi! Unfortunately, we will not be releasing the paragraphs in their original order to avoid copyright infringement and prevent reconstruction of the translations that are not in the public domain. Please note that the paragraphs have also been sampled randomly before shuffling.

**Comment by lighter47** [comment]
Well, thank you for your reply.
